workflows:
  flutter-android:
    name: Yeogiga Android Build
    instance_type: mac_mini_m2  # Codemagic이 쓸 맥 머신
    max_build_duration: 20
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    environment:
      flutter: stable
      groups:
        - android_release_signing

    scripts:
      - name: 🔐 Decode keystore
        script: echo $CM_KEYSTORE | base64 --decode > android/app/keystore.jks

      - name: 📄 Generate key.properties
        script: |
          echo "storePassword=$CM_KEYSTORE_PASSWORD" > android/key.properties
          echo "keyPassword=$CM_KEY_PASSWORD" >> android/key.properties
          echo "keyAlias=$CM_KEY_ALIAS" >> android/key.properties
          echo "storeFile=keystore.jks" >> android/key.properties

      - name: 📦 Install dependencies
        script: flutter pub get

      - name: ✅ Analyze code
        script: flutter analyze

      - name: 🧪 Run tests
        script: flutter test

      - name: 🛠 Build AAB
        script: flutter build appbundle --release

    artifacts:
      - build/app/outputs/bundle/release/app-release.aab

    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        artifact_type: aab