// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA513V_cD4JsddmaXltbaPcmuOuk86UcEo',
    appId: '1:281755074082:web:0b7d5c68062b9bfc7d147b',
    messagingSenderId: '281755074082',
    projectId: 'yeogiga-808f2',
    authDomain: 'yeogiga-808f2.firebaseapp.com',
    storageBucket: 'yeogiga-808f2.firebasestorage.app',
    measurementId: 'G-N1Z8YY30PQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQVnXPuInTCM1lGiQ0BUY_BuJ169IXlGQ',
    appId: '1:281755074082:android:e9487b7a6bf59b507d147b',
    messagingSenderId: '281755074082',
    projectId: 'yeogiga-808f2',
    storageBucket: 'yeogiga-808f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZWVP1tebGzXQ6Y2Qj-O1KzNWYG5yIFLQ',
    appId: '1:281755074082:ios:b07554e24754d9e47d147b',
    messagingSenderId: '281755074082',
    projectId: 'yeogiga-808f2',
    storageBucket: 'yeogiga-808f2.firebasestorage.app',
    iosBundleId: 'com.ilmansa.yeogiga.yeogiga',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZWVP1tebGzXQ6Y2Qj-O1KzNWYG5yIFLQ',
    appId: '1:281755074082:ios:b07554e24754d9e47d147b',
    messagingSenderId: '281755074082',
    projectId: 'yeogiga-808f2',
    storageBucket: 'yeogiga-808f2.firebasestorage.app',
    iosBundleId: 'com.ilmansa.yeogiga.yeogiga',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA513V_cD4JsddmaXltbaPcmuOuk86UcEo',
    appId: '1:281755074082:web:be69090ca84447367d147b',
    messagingSenderId: '281755074082',
    projectId: 'yeogiga-808f2',
    authDomain: 'yeogiga-808f2.firebaseapp.com',
    storageBucket: 'yeogiga-808f2.firebasestorage.app',
    measurementId: 'G-0X0HNTT58M',
  );
}
